export const store = [
  {
    label: 'Leonardo',
    count: 0,
    price: 1,
    multiplier: 1,
    src: './bonus-1.svg',
  },
  {
    label: 'Raphaël',
    count: 0,
    price: 10,
    multiplier: 5,
    src: './bonus-2.svg',
  },
  {
    label: 'Donatello',
    count: 0,
    price: 100,
    multiplier: 10,
    src: './bonus-3.svg',
  },
  {
    label: 'Michelangelo',
    count: 0,
    price: 1000,
    multiplier: 25,
    src: './bonus-4.svg',
  },
  {
    label: 'Splinter',
    count: 0,
    price: 10000,
    multiplier: 50,
    src: './bonus-5.svg',
  },
  {
    label: 'Shredder',
    count: 0,
    price: 100000,
    multiplier: 75,
    src: './bonus-6.svg',
  },
  {
    label: 'Krang',
    count: 0,
    price: 1000000,
    multiplier: 100,
    src: './bonus-7.svg',
  },
  // {
  //   label: 'Splinter',
  //   count: 0,
  //   price: 10000000,
  //   multiplier: 250,
  //   src: './bonus-.svg',
  // },
  // {
  //   label: 'Splinter',
  //   count: 0,
  //   price: 10000000,
  //   multiplier: 500,
  //   src: './bonus-.svg',
  // },
  // {
  //   label: 'Splinter',
  //   count: 0,
  //   price: 100000000,
  //   multiplier: 1000,
  //   src: './bonus-.svg',
  // },
];

export const ninjaAdjectives = [
  'Silent',
  'Big',
  'Sad',
  'Dark',
  'Agile',
  'Fragile',
  'Dumb',
  'Dead',
  'Ghost',
  'Snake',
  'Mysterious',
  'Clumsy',
  'Hollow',
  'Iron',
  'Golden',
  'Gracefull',
  'Invisible',
];

export const ninjaNames = [
  'Killer',
  'Soldier',
  'Assassin',
  'Demon',
  'Hunter',
  'Spider',
  'Bullet',
  'Buildozer',
  'Stalker',
  'Samaritan',
  'Ninja',
  'Thunder',
  'Wolf',
  'Shade',
  'Dagger',
  'Master',
];
